- webwhatsapi/js_scripts/get_unread_messages.js
This patch 
- Fix a bug where unread message not shown up if it come in **under 1 second** of last checked time.
- Checking if it really a user sent messages (don't send scam/block banner)
> Fix "dropped" unread message

- webwhatsapi/js_scripts/send_message_to_phone_number.js
Now, JS file searches for the number in contacts instead chat list, when send_to_phone_number method is called. Issue details: https://github.com/mukulhase/WebWhatsAPI/issues/10
> Solving the #10 issue

- webwhatsapi/__init__.py
- webwhatsapi/objects/contact.py
- webwhatsapi/objects/message.py
- webwhatsapi/objects/whatsapp_object.py
- webwhatsapi/wapi_js_wrapper.py
- You can now pass `chrome_options` argument to constructor with a list of additional options (for example `['headless', 'disable-gpu']`
- Fixed `os.CREAT` to `os.O_CREAT` misspelling
> Added additional Chrome options as constructor argument

- webwhatsapi/__init__.py
- webwhatsapi/js/wapi.js
get_unread function now has a parameter to enable/disable use of unreadCount attribute of Chat objects to retrieve unread messages.
This solves the problem where new messages were received before opening the driver and wouldn't be returned as unread.
If chat is manually marked as unread then the last message of the sender will be returned as unread.
> get_unread now uses unreadCount attribute from Chat object to return unread messages

- webwhatsapi/js/wapi.js
- webwhatsapi/objects/contact.py
- webwhatsapi/objects/message.py
contact.py allow to get the profile_pic attribute and get the short_name
message.py add the force_download parameter to the function save_media in order to save full image. without this parameter only save a miniature image always
wapi.py fix the problem when it is sent a previw link with the function sendMessageWithThumb
> updates for contact.py/message.py/wapi.js

- requirements.txt
Since pull request #297 was incorporated into the code, requirements.txt would need to include installation of python-magic to work properly.
> Update requirements.txt to include python-magic

- webwhatsapi/__init__.py
I noticed a bug in `get_all_chats()` if there are not chats in the conversation.
I get the `TypeError: 'NoneType' object is not iterable` message.
This small change fixed it
> fix bug in get_all_chats

- webwhatsapi/js/wapi.js
- webwhatsapi/objects/whatsapp_object.py
As mentioned on #397 and #389, this command was returning the following error when the checked number doesn't exist:
`TypeError: 'NoneType' object is not subscriptable`
This is due to a recently whatsapp modification that outputs jid as undefined, this said what I did was a check if it's undefined on `wapi.js` and if it is, throws the exception before the first command:
```
window.WAPI.checkNumberStatus = function(id, done) {
window.Store.WapQuery.queryExist(id).then((result) => {
if(done !== undefined) {
if(result.jid === undefined) throw 404;
done(window.WAPI._serializeNumberStatusObj(result));
}
}).catch((e) => {
if(done !== undefined) {
done(window.WAPI._serializeNumberStatusObj({
status: e,
jid: id
}));
}
});
return true;
};
```
Also, I'm running Python 2.7 on Windows Server 2012 and …
> Fix to check_number_status for NoneType bug

- webwhatsapi/__init__.py
Fixed sorting when reading new messages. CID is now null, so it is ordering by timestamp attribute.
Related to issue: https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/403
> Fixed sorting of unread messages (now by timestamp)

- sample/remote.py
Save session on "/firefox_cache/localStorage.json".
Create the directory "/firefox_cache", it's on .gitignore
The "app" directory is internal to docker, it corresponds to the root of the project.
The profile parameter requires a directory not a file.
> Save session cookies to read QR code only once

- webwhatsapi/objects/message.py
When we use the sample remote.py and an image without caption is sent, a reject is thrown. Because I understand that caption should exist, I prefer to define its type string with empty value.
> MediaMessage caption default empty

- webwhatsapi/__init__.py
Bug Fixed  Function group_get_participants.
the error was originated when looking for a serialized id so it did not print the list of participants.
> Bug Fixed group_get_participants id

- webwhatsapi/__init__.py
- webwhatsapi/js/wapi.js
Trying to get a profile picture would never return `done` when the contact is not on your contacts list.
This happens because the promise `window.Store.ProfilePicThumb.find(id)` rejects it if not found.
That's why I'm using the second _optional_ callback of .then(): `Promise.then(onFulfilled[, onRejected]);`
This is an annoying bug because when it's rejected it will hold every following request as `done` couldn't be reached.
I've been testing this edit for some days now and it works without a problem, just keep in mind to have the contact on your contacts list before trying to get their picture, otherwise it will always return false
> Fix to getProfilePics

- webwhatsapi/objects/message.py
MediaMessage were being identified as GeoMessage, i changed this validation to only enter when lat and lng has value.
> fixed how to identify geo messages correctly

- webwhatsapi/js/wapi.js
When the message is vcard type, the displayName can be set on the subtype, hinting the name of the contact to add without having to open the vcard to see the contact name.
Also, removed the dependency on Store.Conn.me since its not needed, and it's not always unpacked properly or on time (still tracing this)
> sendVCard displayName as subtype and undefined Conn fix

- webwhatsapi/objects/contact.py
When specific keys were not in 'js_obj', the local variable would not be set, throwing 'not defined' errors while retrieving contacts
> Fixed contact throwing 'not defined' errors

- webwhatsapi/__init__.py
- webwhatsapi/wapi_js_wrapper.py
After WhatsAPIDriver.quit(), there's an infinite running thread that keeps checking for new messages every 2 seconds, but it raises an exception because it can't connect to browser anymore.
This PR will exit this thread when driver.quit() is called.
> FIX: finish running thread after driver.quit()

- webwhatsapi/__init__.py
- webwhatsapi/wapi_js_wrapper.py
Pull request related to the issue #716 
Solution: 
The WAPI.js injection should be after user logged in WhatsApp
The is_logged_in() function was changed to support login verification even if WAPI.js wasn't injected yet.
> Fix wapi.js injection

- webwhatsapi/__init__.py
Waiting for QR fails with
```
Traceback (most recent call last):
File "log_all.py", line 72, in
driver.wait_for_login()
File "/home/admin/.local/lib/python3.8/site-packages/webwhatsapi/init.py", line 250, in wait_for_login
WebDriverWait(self.driver, timeout).until(
File "/home/admin/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```
Fix taken from: https://github.com/open-wa/wa-automate-python
> Fixing selenium.common.exceptions.TimeoutException: Message:

- webwhatsapi/async_driver.py
When working with your project, I missed a method to check if a specif phone number was able to receive messages, but in an asynchronous manner so I added and tested the same synchronous method to WhatsAPIDriverAsync in order to use it.
closes #949
> Add async check_number_status to WhatsAPIDriverAsync

- webwhatsapi/js/wapi.js
The update method is now not part of each group metadata object, but we can achieve the same functionality from the global `window.Store.GroupMetadata` object.
> Fix group metadata retrieval
