mukulhase/WebWhatsapp-Wrapper

webwhatsapi/js_scripts/get_unread_messages.js
I may or may not have make a mistake in previous PR 😃
=> get_unread_message: Fix reading sent message as unread

.gitignore, webwhatsapi/__init__.py
Use Python 3 `print` function instead of Python 2 and import from `__future__` to works in Python 2
=> Use Python 3 print function instead of Python 2

webwhatsapi/__init__.py
QRCode css selector changed to search for its alt text rather than searching almost randomly.
=> Fix qrCode css selector

Makefile, README.md, pylint.rc, requirements-test.txt, sample/async_echo.py, sample/echo.py, webwhatsapi/__init__.py, webwhatsapi/async_driver.py, webwhatsapi/helper.py, webwhatsapi/js/wapi.js, webwhatsapi/objects/chat.py, webwhatsapi/objects/contact.py, webwhatsapi/objects/message.py, webwhatsapi/objects/whatsapp_object.py
* Add async driver
* Resolved problems with downloads
* Resolved problems with some JS functions
* Get common groups feature
* PEP8
* Remove metaclasses usage. Replaced by factories.
* Move logic from entities to driver
* Other things I can't remember
=> Add async driver

README.md, webwhatsapi/__init__.py, webwhatsapi/js/wapi.js
**send_message_to_id()**
Lets you send message to contacts without chat, or even not added contacts with a simple trick!
Sets first chat's recipient as recipient you want to message, sends message, then reverts original recipient.
Needs at least one existing chat.
Fixes #127 and #87
**getMyContacts()**
When using getAllContacts, unknown numbers was coming up.
Added filtering by "__x_isMyContact" variable in contact data.
**get_qr() custom filename**
Added custom filename option for get_qr function.
**Fixed #128** 
**is_logged_in()**
Lets you check login status async.
for example, I needed to send the QR code when user requested, and also check if user was logged in.
```
while True:
if driver.is_logged_in():
break
if userRequestedQRCode:
userRequestedQRCode = False
base64EncodedQRCode = …
```
=> Add send_message_to_id(), getMyContacts(), custom filename parameter for get_qr, fix #128, add is_logged_in(), add get_qr_plain()

.gitignore, Pipfile, requirements.txt, setup.py, webwhatsapi/__init__.py, webwhatsapi/async_driver.py
Pycrypto module is not supported anymore and is a pain to install on Windows.
I replaced it with the cryptography module.
=> Replace pycrypto with cryptography

README.md, dockerfile, sample/remote.py, sample/test_remote.py, setup.py, webwhatsapi/objects/message.py, webwhatsapi/objects/whatsapp_object.py
Thank you @mukulhase and contributors for this library. Great job!
I made some changes, mainly because I am running it inside Docker containers. Which helps a lot in running a stable and headless environment :-)
* Documentation of a possible Docker setup and installation, dockerfile for base image
* More structure in the README. Still needs some work IMHO.
* Made an example for remote Selenium, which shows most important fields and image download as a starting point for new users
* Made an small script to test remote Selenium
* Added new instance variables for type "chat" and media "caption"
* save_media method only got thumbnails, now downloads full size media stream
* Fixes the filename, which was based on filehash, which may contain invalid filename characters. Filename is now based on …
=> Docker installation, remote example, bugfixes, better docs

webwhatsapi/__init__.py
Auto Create New Chat if no one as found
Thanks to @Spielie
=> Modified get_chat_from_phone_number

webwhatsapi/__init__.py, webwhatsapi/js/wapi.js, webwhatsapi/objects/message.py
- Added GeoMessage to allow a better and transparent way to manage geolocation.
- Added support for multiple vcards on a same message.
- Added possibility to check the device battery.
- Added method to check messages as unread, based on the fact that whatsapp only mark as 'new' message the ones than came directly to whatsapp web, ignoring the messages added when the web is disconnected.
- Unread messages now comes in order from older to newer.
=> New features

README.md
The docker command is different on windows and needs some changes, therefore it should be mentioned in the README
=> Hint how to start docker on Windows

webwhatsapi/objects/message.py, webwhatsapi/wapi_js_wrapper.py
- Added filename return on saving media
- Fixed KeyError exception when receiving image without caption (fix #190 )
=> Minor fixes

README.md
=> Fix line 105 in Readme.md

docker-compose.yml, docker-entrypoint.sh, sample/remote.py
docker-compose gives a stable entrypoint to run this.
for build you can do 
```docker-compose build```
and for run after build
```docker-compose up```
=> Added docker-compose and entrypoint for docker

webwhatsapi/js/wapi.js
Fixed getChats, unreadMessages, and batteryLevel functions
need fix others functions yet
=> window.Store Removed

webwhatsapi/js/wapi.js
add function to sendImage
Fake function to send image to any chat..
how to use..
create group with name DATABASEPICBOT
send images you want to send to this group with caption(captions will be used like a "id" to find image before)
just call this function with "id" image, chat you want to send, and option new caption to this image
=> fixed bug in sendImageFromDatabasePicBot

webwhatsapi/js/wapi.js
Restore window.Store all thanks to -> @karopass
sendMessageWithThumb demo: http://prntscr.com/jnfa3t
=> Restore window.Store, add function sendMessageWithThumb

webwhatsapi/objects/message.py
Added an audio key to crypt_keys in order to decrypt audio files.
=> Add key for decrypting audio files

sample/new_messages_observer.py, webwhatsapi/js/wapi.js, webwhatsapi/wapi_js_wrapper.py
- Add example of new message observer
- Optimize WAPI wrapper to load only once time wapi.js
- Remove unnecessary verification new message listener initialization
=> new message oberserver example, optimization of wrapper

webwhatsapi/js/wapi.js
- Fix #284 -> In the new version of web whatsapp they have deprecated some binary protocols and the setSubProtocol method only uses the deprecated versions. Now we create the object manually using the correct version.
- Fix createGroup method -> the Store.Wap doesn't have the binary protocol anymore.
=> Fix createGroup and conversationDelete

webwhatsapi/__init__.py, webwhatsapi/js/wapi.js
imgBase64 is String like => 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQA......'
thanks to @alfred82santa to find MediaCollection
=> New Function To Send Image or Any Type of File

webwhatsapi/js/wapi.js
Method to use WAPI global object to send one or more contact card to chat.
=> Send one or more contact cards to chat using the chat models ids

webwhatsapi/js/wapi.js
Adding function to send a simple VCARD or a VCARD list to a specific chat without the need for VCARD to belong to a contact. Ability to send all VCARD fields ([https://en.wikipedia.org/wiki/VCard#vCard_3.0](https://en.wikipedia.org/wiki/VCard#vCard_3.0))
=> Send custom VCard or VCard list to a chat

setup.py
'python-magic' also required in Docker
=> Fix issue #316

webwhatsapi/js/wapi.js
Correcting the object copy that is used to the creation of the vCard object. As it was, the first message object of the Store.Msg was be used, but it could occur that the first object being from another user. Fixed to get the first message sent from the logged in user.
=> Correcting the object copy that is used to the creation of the vCard

webwhatsapi/__init__.py, webwhatsapi/js/wapi.js
- Create get_qr_base64 to return in base64 so as not to waste processing when sending it elsewhere
- Fixed a bug in reload qr code, it was not working
=> Get QR Code in Base64 to Get QR Code in Base64 and fixed a bug in reload qr code

webwhatsapi/__init__.py, webwhatsapi/js/wapi.js
- getAllChatIds - Return _serializable or chat id, sometimes the id was coming as an object, causing unexpected results
=>  Improving login checking and adjustment in getAllChatIds

webwhatsapi/objects/chat.py
since there is a chat_send_message, why not send_media
=> add send_media

webwhatsapi/js/wapi.js, webwhatsapi/objects/whatsapp_object.py
- Adjustment in send message to create new chat instead of using the first chat
- Changed deleteConversation function to use chat object sendDelete. That way the view will be updated.
=> Adjustment in send message to create new chat instead of using the first chat

webwhatsapi/js/wapi.js
some functions not return or done if has error locking API. Some functions have many returns.
New id was ajusted in feel functions, I ajust getChat  and pointed out the others to use it by decreasing points in the code to be corrected.
=> update WAPI.js to done and return and ids

webwhatsapi/js/wapi.js
defined misssing leaveGroup function #445
=> New function leaveGroup #445

webwhatsapi/js/wapi.js
It stopped sending media to new chats, this version works for both new chats and old chats.
Thanks to @GeovRodri for the code on the PR #398 
Reported on #440
=> Fix to sendImage

webwhatsapi/objects/contact.py
When I connect to the bot using whatsapp bussines the name of the contact appears with the cell phone number instead of using the registered name.
formattedName returns the phone number formatted instead of the registered name
I found that the fields pushname and shortName do not contain data but the field verifiedName has the correct name.
Based on the above, I added a new attribute to the contact structure (self.verified_name) and modify the function get_safe_name so that it returns the name used by verifiedName when the first character is a + sign.
I do not know if this problem are present in another situations.
Here is the contact's structure:
'chat': {'archive': False,
'changeNumberNewJid': None,
'changeNumberOldJid': None,
'contact': {'formattedName': '+54 9 11 XXXX-XXXX',
'id': …
=> problems getting the user's name

sample/flask/Pipfile, sample/flask/Pipfile.lock, sample/flask/log.txt, sample/flask/webapi.ini, sample/flask/webapi.py, sample/flask/wsgi.py, webwhatsapi/__init__.py
Bug Fix
In group_get_participants, added _serialized while calling get_contact_from_id
Improvements
Added a sample flask app to run an API version of the repo
=> Bug Fix & Added a sample flask application

webwhatsapi/objects/chat.py
https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/322
=> Fixed issue on chat.get_messages()

sample/log_all.py
=> A simple logger of everything

webwhatsapi/__init__.py
=> Add executable_path arg in __init__.py

webwhatsapi/js/wapi.js
More bug fixes and improvements.
Special thanks to @Theblood
=> Update wapi.js MORE BUG FIXES AND IMPROMENTS

webwhatsapi/__init__.py
Change qr div selector from ._2EZ_m to div[data-ref] to avoid using the dynamic class name
=> Change qr div selector

webwhatsapi/__init__.py, webwhatsapi/js/wapi.js
This function check if phone is connected to the internet. It isn't the same of checking if user is logged in.
Example:
```python
if driver.is_connected() is False:
print("Phone disconnected from the internet")
```
=> New Function: isConnected

webwhatsapi/js/wapi.js
It solved this problem:
#761 chat.sendMessage is not a function
=> Fix Missing ChatClass

webwhatsapi/js/wapi.js
A small update to the deleteMessage function
=> Update to wapi.js resolves #776

Dockerfile
referenced inside the requirements.txt
=> copy requirements into container

webwhatsapi/__init__.py
Hi,
There were no handler for user defined executable_path path in Chrome condition. So I have added few lines to handle user defined executable_path for chrome.
Thanks...
=> user defined executable_path for chrome driver

webwhatsapi/__init__.py
add str chatid in get_all_messages_in_chat
=> add str chatid in get_all_messages_in_chat
